services:
  frontend:
    build: 
      context: ./states-countries-ts
      target: base
    ports: 
      - 5173:5173
    volumes:
      - ./states-countries-ts:/app
  api:
    build: 
      context: ./states-countries-api
      target: base
    ports:
      - 5257:5257
    volumes:
      - ./states-countries-api:/app
    depends_on:
      - db
    environment:
      DOTNET_ENVIRONMENT: Development
  db:
    container_name: states-countries-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment: 
      SA_PASSWORD: "This_is_very_secure"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: