services:
  frontend:
    build: ./states-countries-ts
    ports: 
      - 5173:5173
    volumes:
      - ./states-countries-ts:/app
  api:
    build: ./states-countries-api
    ports:
      - 5257:5257
    volumes:
    - ./states-countries-api:/app