// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatesCountriesApi.Models;

#nullable disable

namespace states_countries_api.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20240725175703_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StatesCountriesApi.Models.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "MX",
                            Name = "Mexico"
                        });
                });

            modelBuilder.Entity("StatesCountriesApi.Models.State", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "VA",
                            CountryId = 1L,
                            Name = "Virginia"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "FL",
                            CountryId = 1L,
                            Name = "Florida"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "ON",
                            CountryId = 2L,
                            Name = "Ontario"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "MXC",
                            CountryId = 3L,
                            Name = "Mexico City"
                        });
                });

            modelBuilder.Entity("StatesCountriesApi.Models.State", b =>
                {
                    b.HasOne("StatesCountriesApi.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("StatesCountriesApi.Models.Country", b =>
                {
                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
